version: '3'
services:
  my.top.api:
    image: ghcr.io/sudactudak/my-top-api:master
    container_name: my_top_api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./.env:/opt/app/.env
